version: "3.5"

services:
  cnpeducation_build:
    build: ../
    container_name: "cnpeducation_build"
    volumes:
      - dist:/usr/src/app/dist

  cnpeducation_web:
    image: nginx
    ports:
      - 8081:80
    container_name: "cnpeducation_web"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
